### ISSUE TITLE
今後の方針について

### ISSUE THREAD

**Issue by ryosebach** [SuzukiYuka/PlatformGame#1]
### ワンアクション足す
- 攻撃
 - 敵を攻撃する
   - 雑魚敵, ボス
 
### ステージへのアクション
  - 謎解き
  - 反転, 回転 (大きなアクションでは設計レベルで考えるべき)

### 制約
- 光と闇

### 世界観
- 色
- 光
- キャラ，ストーリー

### リスクリターン
- 駆け引きを行いたくなる仕掛け

## ゲームにおいて

- コードで作る
- デザインで作る部分

**Comment by SuzukiYuka** [comment]
じゃんけん

**Comment by SuzukiYuka** [comment]
[世界観]
キーボード
セキュリティ
ウイルス
PC修理

**Comment by ryosebach** [comment]
キーが使えない間(クリアしていない間)は
制約があってもいいかも？？？

**Comment by SuzukiYuka** [comment]
キーをクリア→ショートカットとしてのアクション、機能が開放される

**Comment by SuzukiYuka** [comment]
キーボードのウイルス倒した → 病気のウイルス
キーボードの機能追加 → ワクチン作る
by りょうさん

**Comment by ryosebach** [comment]
ふむふむ，これも面白いかもだなぁ

**Comment by SuzukiYuka** [comment]
プログラミングで寄せようかなー

**Comment by SuzukiYuka** [comment]
https://www.youtube.com/watch?v=MbWK8bCAU2w&feature=youtu.be&list=PLFt_AvWsXl0f0hqURlhyIoAabKPgRsqjz
